version: "3.3"

services:
  # Set up environment for mariadb database
  database:
    image: mariadb:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: art_gallery
      MYSQL_USER: jwm
      MYSQL_PASSWORD: jwm
    networks:
      - mynet


  # Set up environment for redis
  redis:
    image: redis:latest
    container_name: myredis
    restart: always
    networks:
      - mynet


  # Set up environment for PHP-FPM
  php-fpm:
    privileged: true
    build:
      context: ./src/php           # use customized dockerfile to add extension
      dockerfile: dockerfile
    container_name: myphp
    depends_on:
      - database
      - redis
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
    networks:
      - mynet


  nginx:
    image: nginx:latest
    container_name: mynginx
    depends_on:
      - php-fpm
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    networks:
      - mynet


  php:
    image: phpmyadmin:latest
    container_name: phpMyAdmin
    ports:
      - "8082:80"
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_USER: jwm
      MYSQL_PASSWORD: jwm
    networks:
      - mynet

volumes:
  database:

networks:
  mynet:
    driver: bridge
